## https://docs.travis-ci.com/user/languages/r/
## https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis

language: r
r: devel
sudo: false
cache: packages

apt_packages:
  - texlive-latex-extra

r_github_packages:
  - jimhester/covr

env:
 - LME4_TEST_LEVEL=2

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - test_mods
