## https://docs.travis-ci.com/user/languages/r/
## https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis

language: r
r: devel
sudo: false
cache: packages

## https://docs.travis-ci.com/user/installing-dependencies/
## this is the only extra package we need, and it's whitelisted,
## so we can leave 'sudo: false' above and get a big speed boost
addons:
  apt:
    packages:
    - texlive-latex-extra

r_github_packages:
  - jimhester/covr

env:
 - LME4_TEST_LEVEL=2


script :

## https://github.com/travis-ci/travis-ci/issues/3849
## https://github.com/travis-ci/travis-ci/issues/5469
## https://github.com/dbailleul/RClone/blob/9d63bcf5be8113b789f562c39dc7ca2ca7600cd5/.travis.yml
 - travis_wait 30 R CMD build --no-build-vignettes
 - travis_wait 30 R CMD check "${PKG_FILE_NAME}" --no-build-vignettes
    
## need travis_wait because checks take 10+ minutes ...
after_success:
  - travis_wait Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - test_mods
